stages:
  - build
  - publish

variables:
  HELM_REGISTRY: $CI_SERVER_HOST
  HELM_REGISTRY_USER: $CI_REGISTRY_USER
  HELM_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD


build:
  stage: build
  tags:
    - docker
  script:
    - apk add --no-cache curl jq openssl
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | sh
    - helm version
    - echo "Building Helm Chart..."
    - helm lint ./charts
    - helm package ./charts
  artifacts:
    paths:
      - "*.tgz"



publish:
  tags:
    - docker
  image: curlimages/curl:latest
  stage: publish
  script:
    - 'curl --fail-with-body --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@deusops-may-1.5.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
